# Generated by Django 3.0.6 on 2020-12-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=1000)),
                ('lastname', models.TextField(max_length=1000)),
                ('salary', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
    ]
