# Generated by Django 3.0.6 on 2020-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
